# BLobby by Bradley Steele (Ibiza).
#
# /Contact
# Spigot: https://www.spigotmc.org/members/292138/
# Discord: Bradley#4169
# Discord Support Server: https://redirect.bradleysteele.me/bps


# Do not change this number. You will be notified if a new
# configuration version is available.
config-version: 1


server:

  # List of world names which you do NOT want the following
  # settings to be applied to.
  excluded-worlds:
  - build_world


  # Prevents entities from spawning, apart form those spawned
  # by other plugins.
  disable-entity-spawn: true

  # Resets the time to 0 every 10 minutes.
  disable-night: true

  # Prevents rain and storms.
  disable-weather: true

  # Prevents hunger loss.
  disable-hunger: true

  # Prevents all damage from being received by players.
  disable-damage: true


  # Note: The following are ignored with the permission
  # node: blobby.bypass

  # Prevents blocks being broken.
  disable-block-break: true

  # Prevents blocks being placed.
  disable-block-place: true

  # Prevents ground items from being picked up.
  disable-pickup: true

  # Prevents players from dropping items.
  disable-drop: true

  chat:

    # If the chat should be handled by BLobby.
    handle: true

    # Prevents players from talking in chat.
    disable: false

    format:

      # The fallback format and format used if Vault is
      # not  a present plugin.
      default: '{name}&f: {message}'

      # The formats for individual groups, requires Vault.
      # Note: groups are case-sensitive.
      groups:
        owner: '{prefix}{name}&f: &c{message}'
        default: '{prefix}{name}&f: &7{message}'


join:

  # The message to send when a player joins the server.
  # {player} will be replaced with the player name, leave
  # empty '' to not send any message.
  message: ''

  # The message of the day to send to the player upon
  # joining. Set to 'motd: []' without quotes to remove.
  motd:
  - '&8&m-------------------------------------------'
  - '&6BLobby'
  - '&7www.bradleysteele.me'
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&8&m-------------------------------------------'

  # Teleports the player to spawn upon joining.
  spawn: true


quit:

  # The message to send when a player leaves the server.
  # {player} will be replaced with the player name, leave
  # empty '' to not send any message.
  message: ''


spawn:

  # The gamemode players will spawn in, will fallback to
  # survival if the provided gamemode is invalid.
  gamemode: ADVENTURE

  # Players will be teleported to the spawn location if
  # they take damage from the void.
  on-void: true

  # Teleports all players to spawn when the plugin is enabled.
  on-enable: true

  # Enables the /spawn command for all players.
  command: true


sidebar:

  # If the sidebar is enabled.
  enabled: true

  # The title of the sidebar.
  title: '&6BLobby'

  # Text for each line of the sidebar. Each line is limited
  # to 32 characters, including colours. With a maximum of
  # 16 lines.
  content:
  - '&8&m----------------------------'
  - '&6BLobby'
  - ''
  - '&7Welcome &e{player}&7, enjoy'
  - '&7your stay!'
  - ''
  - ''
  - '&8&m----------------------------'
  - '&7www.bradleysteele.me'