name: ${project.name}
author: Bradley Steele (Ibiza)
description: ${project.description}
version: ${project.version}
main: me.bradleysteele.lobby.BLobby
depend: [BCommons]
softdepend: [Vault]
api-version: 1.13